#!/bin/bash

#PBS -l select=1:ncpus=32:ngpus=4:mem=184gb
#PBS -l walltime=60:00:00
#PBS -M yuenyuen.chan@student.unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5313567/results/Output_test_Report

###---------------------------------------------------------------------------

cd /srv/scratch/z5313567

source anaconda3/bin/activate py3.10

echo ""$(date)"" 2>&1 | tee -a /srv/scratch/z5313567/thesis/wav2vec2/output/Renee_myST_OGI_TLT/Renee_finetune_myST-OGI-TLT_output2.txt

cd /srv/scratch/z5313567/thesis/wav2vec2/code

python Renee_run_finetune_kids_myST-OGI-TLT.py 2>&1 | tee -a /srv/scratch/z5313567/thesis/wav2vec2/output/Renee_myST_OGI_TLT/Renee_finetune_myST-OGI-TLT_output2.txt

conda deactivate
conda deactivate