#!/bin/bash

#PBS -l select=1:ncpus=32:ngpus=4:mem=184gb
#PBS -l walltime=12:00:00
#PBS -M yuenyuen.chan@student.unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5313567/results/Output_test_Report

###---------------------------------------------------------------------------

cd /srv/scratch/z5313567

source anaconda3/bin/activate py3.10

echo ""$(date)"" 2>&1 | tee -a /srv/scratch/z5313567/thesis/wav2vec2/output/OGI_American/10hour/10hour_Finetune_Wav2vec2_American_output1.txt

cd /srv/scratch/z5313567/thesis/wav2vec2/code/OGI_American

python Finetune_Wav2vec2_American_10hour.py 2>&1 | tee -a /srv/scratch/z5313567/thesis/wav2vec2/output/OGI_American/10hour/10hour_Finetune_Wav2vec2_American_output1.txt

conda deactivate
conda deactivate