#!/bin/bash

#PBS -l select=1:ncpus=16:ngpus=2:mem=92gb
#PBS -l walltime=12:00:00
#PBS -M yuenyuen.chan@student.unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5313567/results/Output_test_Report

###---------------------------------------------------------------------------

cd /srv/scratch/z5313567

source anaconda3/bin/activate py3.10

echo ""$(date)"" 2>&1 | tee -a /srv/scratch/z5313567/thesis/hubert/output/AusKidTalk/AusKidTalk_output25_progressive_finetune_AusTalk_CU_AusKidTalk_freeze_lower_3_transformer_layers_lowercase.txt

cd /srv/scratch/z5313567/thesis/hubert/code

python hubert_progressive_finetune_AusTalk_CU_AusKidTalk_freeze_lower_transformer_lowercase.py 2>&1 | tee -a /srv/scratch/z5313567/thesis/hubert/output/AusKidTalk/AusKidTalk_output25_progressive_finetune_AusTalk_CU_AusKidTalk_freeze_lower_3_transformer_layers_lowercase.txt

conda deactivate
conda deactivate