#!/bin/bash

#PBS -l select=1:ncpus=16:ngpus=2:mem=92gb:gpu_model=A100
#PBS -l walltime=12:00:00
#PBS -M yuenyuen.chan@student.unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5313567/results/Output_test_Report

###---------------------------------------------------------------------------

cd /srv/scratch/z5313567

source anaconda3/bin/activate py3.10

echo ""$(date)"" 2>&1 | tee -a /srv/scratch/z5313567/thesis/whisper/output/AusTalk/AusTalk_output3_finetune_medium_en_lowercase.txt

cd /srv/scratch/z5313567/thesis/whisper/code

python whisper_medium_en_finetune_AusTalk_lowercase.py 2>&1 | tee -a /srv/scratch/z5313567/thesis/whisper/output/AusTalk/AusTalk_output3_finetune_medium_en_lowercase.txt

conda deactivate
conda deactivate