#!/bin/bash

#PBS -l select=1:ncpus=32:ngpus=4:mem=184gb
#PBS -l walltime=40:00:00
#PBS -M yuenyuen.chan@student.unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5313567/results/Output_test_Report

###---------------------------------------------------------------------------

cd /srv/scratch/z5313567

source anaconda3/bin/activate py3.10

echo ""$(date)"" 2>&1 | tee -a /srv/scratch/z5313567/thesis/wav2vec2/output/AusKidTalk/AusKidTalk_output7_finetune.txt

cd /srv/scratch/z5313567/thesis/wav2vec2/code

python finetune_AusKidTalk_OGImodel.py 2>&1 | tee -a /srv/scratch/z5313567/thesis/wav2vec2/output/AusKidTalk/AusKidTalk_output7_finetune.txt

conda deactivate
conda deactivate