#!/bin/bash

#PBS -l select=1:ncpus=16:ngpus=2:mem=92gb
#PBS -l walltime=35:00:00
#PBS -M yuenyuen.chan@student.unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5313567/results/Output_test_Report

###---------------------------------------------------------------------------

cd /srv/scratch/z5313567

source anaconda3/bin/activate py3.10

echo ""$(date)"" 2>&1 | tee -a /srv/scratch/z5313567/thesis/wav2vec2/output/OGI_American/full_scripted_spontaneous_combined/OGI_scripted_spontaneous_combined_lowercase_output2_finetune.txt

cd /srv/scratch/z5313567/thesis/wav2vec2/code

python finetune_OGI_scripted_spontaneous_combined_lowercase.py 2>&1 | tee -a /srv/scratch/z5313567/thesis/wav2vec2/output/OGI_American/full_scripted_spontaneous_combined/OGI_scripted_spontaneous_combined_lowercase_output2_finetune.txt

conda deactivate
conda deactivate