#!/bin/bash

### Below are directives which correspond to certain flags that are used by the PBS system
### All are prefixed with #PBS followed by the flag and the variable value
### An explanation of the use of the variables can be found
### on github under the HPC-Basics directory titled "pbs-variables.pbs"

#PBS -l select=1:ncpus=1:mem=8gb
#PBS -l walltime=01:00:00
#PBS -M yuenyuen.chan@student.unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5313567/results/Output_test_Report

###---------------------------------------------------------------------------

cd /home/z5313567

source anaconda3/bin/activate py3.10

echo ""$(date)"" 2>&1 | tee -a /srv/scratch/z5313567/thesis/Code/test_python2_venv_example/outputs/test_output1.txt

cd /srv/scratch/z5313567/thesis/Code/test_python2_venv_example/

python python2-venv-example.py 2>&1 | tee -a /srv/scratch/z5313567/thesis/Code/test_python2_venv_example/outputs/test_output1.txt

conda deactivate